Make MaterialTextField's BackgroundColor works with a global style
contrix09/XF-Material-Library pull request #363
Opened 2020-08-30 17:12 UTC by softlion

### :sparkles: What kind of change does this PR introduce? (Bug fix, feature, docs update...)

Bug fix

### :arrow_heading_down: What is the current behavior?

When setting the BackgroundColor property of a MaterialTextField in a Style in App.xaml, it is ignored.

### :new: What is the new behavior (if this is a feature change)?

It is applied as expected.
This is not a feature change.

### :boom: Does this PR introduce a breaking change?

No

### :bug: Recommendations for testing

Sample project updated: a global style has been added and the sample page for MaterialTextField has been udpated.

I renamed the override of BackgroundColor to RealBackgroundColor, but i also detected all changes to BackgroundColor and they are applied to the RealBackgroundColor property before forcing the BackgroundColor to transparent.

The issue was caused by this override of BackgroundColor. When the style is set in App.xaml, BackgroundColor was applied to the base BackgroundColor property, not the override. This is because the override never overrides when the control is casted to a base class. And this is why using "new" to override is a very bad practice.

### :thinking: Checklist before submitting

- [X] All projects build
- [X] Follows style guide lines 
- [ ] Relevant documentation was updated
- [X] Rebased onto current develop

2020-08-30 17:21 UTC, martijn00 commented
@softlion sorry, can you rebase this too?

2020-08-30 17:34 UTC, softlion commented
done

2020-08-30 17:40 UTC, softlion commented
done. I was unable to rebase with visual studio. some kind of bug in this git ui. so i merged.

2020-08-30 20:07 UTC, martijn00 requested changes

2020-08-30 20:07 UTC, martijn00 commented on XF.Material/UI/MaterialTextField.xaml.cs
> +        public Color RealBackgroundColor
Not sure if i like the name RealBackgroundColor... Do you have better ideas instead of `Real`?

2020-08-31 03:51 UTC, softlion commented
They have the same issue on a xamarin forms control out of the box. 
They called it Color.
Not sure it is better ...
It could be CardBackgroudColor.

2020-08-31 09:41 UTC, martijn00 commented
I like `CardBackgroudColor`. Lets go for that.

2020-08-31 10:39 UTC, softlion commented
done

2020-08-31 11:43 UTC, merged