Fix MaterialButton icons and shrinking with ellisis issues on iOS
contrix09/XF-Material-Library pull request #379
Opened 2020-09-19 14:37 UTC by softlion

# :sparkles: What kind of change does this PR introduce? (Bug fix, feature, docs update...)

### :arrow_heading_down: What is the current behavior?

### :new: What is the new behavior (if this is a feature change)?

### :boom: Does this PR introduce a breaking change?

### :bug: Recommendations for testing

### :memo: Links to relevant issues/docs

### :thinking: Checklist before submitting

- [ ] All projects build
- [ ] Follows style guide lines 
- [ ] Relevant documentation was updated
- [ ] Rebased onto current develop

2020-09-20 21:29 UTC, softlion commented
Fixes https://github.com/Baseflow/XF-Material-Library/issues/368

2020-09-21 14:48 UTC, martijn00 requested changes

2020-09-21 14:48 UTC, martijn00 commented on Samples/MaterialMvvmSample.iOS/MaterialMvvmSample.iOS.csproj
> +    <CodesignKey>Apple Development: Benjamin Mayrargue (4FX9X5DS74)</CodesignKey>
Can you revert this? And other personal things?

2020-09-21 14:48 UTC, martijn00 commented on XF.Material/Platforms/Android/Renderers/MaterialButtonRenderer.cs
> +        /// TODO: obsolete. Replaced by Button.CharacterSpacing.
Cleanup?

2020-09-21 15:16 UTC, softlion commented
I abandon using the material buttons. They are complelty buggy and they won't fix. I just removed them all and wont fix them. You can delete the PR, it fixes some things but not all.

2020-12-22 16:05 UTC, closed without merging